name: Release
on:
  push:
    tags:
      - v*.*.*

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  MACOSX_DEPLOYMENT_TARGET: 10.12

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            args: ""

          - os: macos-latest
            args: "--target aarch64-apple-darwin"

          - os: macos-latest
            args: "--target x86_64-apple-darwin"

          - os: windows-latest
            rustflags: -C target-feature=+crt-static
            args: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | checkout
        uses: actions/checkout@v5

      - name: Setup | install node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup | install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Setup | install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup | install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Build | pnpm install
        run: pnpm install

      - name: Build | tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=4096"
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "${{ github.ref_name }}"
          releaseBody: "Release ${{ github.ref_name }}"
          releaseDraft: true
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          includeUpdaterJson: true
          args: ${{ matrix.args }}
